NULL = 0
PLAYER_1 = 1
PLAYER_2 = 2

grid = [[NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL],
        [NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL],
        [NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL],
        [NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL],
        [NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL],
        [NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL],
        [NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL],
        [NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL],
        [NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL],
        [NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL]]

def play(position = (0, 0), player = PLAYER_1):
    print ("Foo")
    